#include <string.h>

#include "../../commons/src/dbg.h"
#include "minunit.h"

#include "../src/lib/miptp_job.h"


char *test_MIPTPJob_create_destroy() {
    MIPTPJob *job = MIPTPJob_create("Hello", strlen("Hello"), 1000);
    mu_assert(job != NULL, "Failed to create MIPTPAppController");
    mu_assert(job->sliding_window.sequence_base == 0, "SlidingWindow base is wrong");
    mu_assert(job->sliding_window.sequence_max == WINDOW_SIZE + 1, "SlidingWindow max is wrong");
    mu_assert(job->sliding_window.window_size == WINDOW_SIZE, "SlidingWindow window_size is wrong");
    mu_assert(job->timeout_len == 1000, "Timeout is wrong");
    mu_assert(strncmp(job->data, "Hello", strlen("Hello")) == 0, "data is wrong");

    MIPTPJob_destroy(job);
    
    return NULL;
}

char *test_MIPTPJob_next_package() {

    // 1600 bytes
    char *data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQPONMLKJIHGFEDCB";
    MIPTPJob *job = MIPTPJob_create(data, strlen(data), 1000);
    printf("data size: %d\n", strlen(data));

    MIPTPPackage *first_package = MIPTPJob_next_package(job, 0);
    mu_assert(first_package != NULL, "Failed to create the first package");
    mu_assert(first_package->data_size == 1492, "Wrong data size in first package");

    MIPTPPackage *second_package = MIPTPJob_next_package(job, 1);
    mu_assert(second_package != NULL, "Failed to create the second package");
    mu_assert(second_package->data_size == 108, "Wrong data size in second package");

    MIPTPPackage *third_package = MIPTPJob_next_package(job, 2);
    mu_assert(third_package == NULL, "There should not be a third package, all the data is consumed");
    
    MIPTPPackage_destroy(first_package);
    MIPTPPackage_destroy(second_package);
    MIPTPJob_destroy(job);
    
    return NULL;
}


char *all_tests(){

    mu_suite_start();
    mu_run_test(test_MIPTPJob_create_destroy);
    mu_run_test(test_MIPTPJob_next_package);

    return NULL;
}

RUN_TESTS(all_tests);