name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: make tests
      run: make tests
    - name: deploy
      env: # Or as an environment variable
        SSH_KEY: ${{ secrets.VM_SSH_KEY }}
      run: |
        touch vm_key
        echo $SSH_KEY > vm_key
        scp -i vm_key -r /bin debian@158.37.63.151:/~
        rm -f vm_key

